server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vuepring
    username: vuepring
    password: vuepring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # 수정시 주의

springdoc:
  packages-to-scan: com.api.backend
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true