server.port: 8080

# spring:
#   datasource:
#     url: jdbc:mysql://111.111.111.11:3306/mallstore_v35_new_kyochonfnb
#     username: mallshoppingV35
#     password: ahftmxhdj
#     driver-class-name: com.mysql.cj.jdbc.Driver